changed files that needed to be changed, and added errors that trace through program pipes

diff --git a/bashuntu b/bashuntu
--- a/bashuntu
+++ b/bashuntu
@@ -1,23 +1,35 @@
 #!/bin/bash
+# This serves as the main entry point to the pseudo-shell.
 
-# This serves as the main entry point to the script. For the time being (i.e. for the group's benefit)
-# I'm going to leave the high-level "structure and flow" comments in place, with the code that does that
-# comment's task immediately after. For instance, if a comment read "echo result back to user" then the code
-# would look like:
+set -o pipefail		# trace error through pipes
+set -o errtrace		# trace error through "time command" and other functions
 
-# Echo result back to user
-#echo "$result"
+# Function for catching and printing errors through pipes
+	# The syntax for calling this to correctly output errors is:
+	# trap 'error ${LINENO} ${?}' ERR
+error() {
+	job="$0"
+	last_line="$1"
+	last_error="$2"
+	echo "ERROR in ${job} : line ${last_line} with exit code ${last_error}"
+	exit 1
+}
 
-# Okay, onto the script itself.
+root_dir=$(pwd)
 
-# High level description:
-does_admin_account_exist=$(cat users.txt | grep "admin")	# 1. Check file for admin account
-
-if [[ $does_admin_account_exist == *"admin"* ]]; then	# 2. Does account "admin" exist?
-  echo "WARNING! Admin account has not been setup yet! Creating Admin account now..."
-  ./setup_admin.sh	# 2a. YES	-> admin account needs to be created. Run setup_admin.sh
-else
-  echo "Initializing shell...[ok]"
-  echo "Proceeding to login screen..."
-  ./login.sh	# 2b. NO 	-> admin account has been created. Run login.sh
+echo -n "Initializing shell..."
+if does_admin_account_exist=$(cat $root_dir/system_files/config/users | grep "admin"); then
+	if [[ $does_admin_account_exist == *"admin"* ]]; then
+		echo "[ok]"
+		echo "WARNING! Admin account has not been setup yet! Creating Admin account now..."
+		if $root_dir/system_files/bin/sys_bin/setup_admin; then
+			echo "Proceeding to login screen..."
+			$root_dir/system_files/bin/sys_bin/login
+		else trap 'error ${LINENO} ${?}' ERR
+		fi
+	else
+		echo "Proceeding to login screen..."
+		./login.sh	# 2b. NO 	-> admin account has been created. Run login.sh
+	fi
+else trap 'error ${LINENO} ${?}' ERR
 fi
